"""empty message

Revision ID: c5c9535b777a
Revises: 
Create Date: 2021-03-09 23:21:14.467394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c9535b777a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('cpf', sa.String(length=20), nullable=False),
    sa.Column('pis', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('municipio', sa.String(length=20), nullable=False),
    sa.Column('cep', sa.String(length=20), nullable=False),
    sa.Column('rua', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('complemento', sa.String(length=20), nullable=True),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    op.create_index(op.f('ix_usuarios_pis'), 'usuarios', ['pis'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_pis'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
